[고지원] Add: product/views.py 추가
wecode-bootcamp-korea/11-weline-backend pull request #5
Opened 2020-08-22 14:09 UTC by Gxone

- color와 product 중간테이블 삭제
- product 테이블 수정

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!
	 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

color와 product의 n:m 관계를 1:n 관계로 수정했습니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-24 03:52 UTC, lordmyshepherd requested changes

2020-08-24 03:52 UTC, lordmyshepherd commented on product/views.py
> +        if Product.objects.filter(id = product_id).exists():
위와 같이 ORM을 사용하실 경우에,
`.exists()` 할 때, db hit 1번, `.get()` 할 때, db hit 1번 `총 2번 ` db에서 data를 조회하게 됩니다.

```suggestion
        try:
            product = Product.objects.get(id=product_id).select_related('image_url')
            result = {
                "id" : product.id,
                "name" : product.name,
                "description" : product.description,
                "price" : product.price,
                "color" : product.color,
                "image_urls" : product.image_url.replace("[", "").replace("]", "")
            }
            return JsonResponse(result, status=200) 
        except Product.DoesNotExist:
            return JsonResponse({"MESSAGE" : "IVALED_HOST"}, status=404) 
                
```

2020-08-24 03:52 UTC, lordmyshepherd commented on product/views.py
> +                    image_url_list = image_url_list.replace("[", "")
replace를 사용하는 이유가 뭔가요??

2020-08-24 03:52 UTC, lordmyshepherd commented on product/views.py
> +            image_url_list = prod_image_url.image_url
replcae를 사용하신 것을 보니, 하나의 상품에 여러 이미지가 있을 때, image table에 한 컬럼에 모든 이미지를 string 형식으로 넣어놓으신 것 같아요.

product image는 한 column에 모든 image url을 넣지 마시고, one to many 관계로 만들어주세요!

2020-08-24 03:52 UTC, lordmyshepherd commented on product/views.py
> +        #     name_categorys.add(prod_name)
주석은 지워주세요~

2020-08-24 03:52 UTC, lordmyshepherd commented on product/views.py
> +class ProductCategoryListView(View):
ProductDetailView를 참고해서 작성해주세요~

2020-08-24 03:52 UTC, lordmyshepherd commented on product/views.py
> +class ProductListView(View):
productdetailview를 참고해서 수정해주세요~
productslist 보다는 products 만으로 충분할 것 같습니다.
```suggestion
class ProductsView(View):
```

2020-08-24 03:52 UTC, lordmyshepherd commented on product/views.py
> +class ProductDetailView(View):
여기도,
```suggestion
class ProductView(View):
```

2020-08-24 05:08 UTC, Gxone commented on product/models.py
> +class ProductName(models.Model):
이름이 같고 색이 다른 상품을 각각 다른 url에서 보여줘서 서로 다른 객체라고 생각했었어요. 그래서 이름도 1:n 관계로 수정 했는데 구현하다보니 잘못 생각한 것 같아서 좀 더 생각해봐야할 것 같아요..

2020-08-24 05:14 UTC, Gxone commented on product/views.py
> +                    image_url_list = image_url_list.replace("[", "")
url을 리스트로 보내주기로했는데 url이 char 필드라 "["a", "b"]" 이런 식으로 배열이 스트링으로 감싸져서 가더라구요. 그래서 [와 ]을 없애고 split으로 배열을 만들어서 보냈어요.

2020-08-24 05:21 UTC, Gxone commented on product/views.py
> +            image_url_list = prod_image_url.image_url
크롤링하면서 csv 파일에 넣을 때 반복되는 행이 생기는데 그걸 데이터베이스에 저장할 때 한 for문에서 어떻게 넣을 지 고민하다가 리스트로 넣었는데 이대로 프론트 분들이 구현을 하셔서 한 번 얘기해보고 수정하도록 할게요!

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +from .models import *
`import *`은 사용하지 않습니다. 현재 불러올 클래스 명을 정확하게 지칭해주세요~

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +            prod = Product.objects.get(id = product_id)
`prod`는 함축적으로 사용할 수 있는 변수명이긴 하지만 product로 정확한 단어를 변수로 사용하시는 것이 좋습니다.

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +            prod_price = prod.price
따로 변수로 먼저 선언하지 않고 더 밑에 선언하신 `body` 딕셔너리에서 바로 사용하셔도 됩니다. 변수가 사용되는 때보다 한참 먼저 변수가 선언되면, 어떻게 쓰이는지, 왜 선언되었는지 흐름상 이해하기가 어려울 수 있기 때문입니다. 그리고 `prod_id` 를 한 번밖에 사용하지 않기 때문에 따로 선언하지 않으셔도 될 것 같아요 👍

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +            prod_color = ProductColor.objects.filter(product = product_id) # object
데이터 객체 (`ProductColor`)에 한 번 접근할 때마다 db hit이 생기게 됩니다.
이미 prod 라는 하나의 대상을 결정하셨기 때문에, 프로덕트 컬러 객체를 프로덕트 아이디로 필터링 하기 보다는 prod가 가지고 있는 color 객체에 접근하시는 방법을 추천드립니다. 

hint) prod의 이름에 접근할 때 -> prod.name. 그렇다면 prod의 컬러에 접근할 때는 ?!

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +            image_url_list = Image.objects.filter(product = product_id)
`ProductColor` 객체와 마찬가지입니다 👍 try it !

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +                color_imgs.append(c.color_image)
리스트 컴프리헨션의 형태로 바꾸어보세요. 일반 for loop 보다 리스트 컴프리헨션이 보통 2배 정도 빠릅니다 :)

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +                urls.append(image.image_url)
리스트 컴프리헨션의 형태로 바꾸어보세요. 일반 for loop 보다 리스트 컴프리헨션이 보통 2배 정도 빠릅니다 :)

2020-08-26 01:33 UTC, soheon-lee commented on product/views.py
> +                # "urls"         :
사용하지 않는 키라면 삭제해주세요

2020-08-26 11:02 UTC, merged