Add : 회원가입, 로그인 views.py구현
wecode-bootcamp-korea/11-weline-backend pull request #8
Opened 2020-08-24 08:46 UTC by miretta96

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-24 10:00 UTC, soheon-lee commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status = 401)
else를 사용하지 않아도 위 if문이 만족하지 않아서 return되지 않는다면 아래 로직에 도달하게 됩니다.
따라서 굳이 필요하지 않은 else는 사용하지 않는 것이 보다 파이썬답습니다

2020-08-25 01:43 UTC, miretta96 commented on user/urls.py
> +    path('signin',SignInView.as_view())
네 프로젝트 url  부분에 user/ 라고 붙였습니다

2020-08-25 01:53 UTC, miretta96 commented on user/views.py
> +
회원가입된 사용자 목록을 불러오는 함수입니다. 확인용으로 작성하였습니다

2020-08-25 03:23 UTC, soheon-lee commented on user/urls.py
> +    path('signin',SignInView.as_view())
네 프로젝트에서 url 모두 빼시고 앱 url에서 슬래시 붙이는 규칙 지켜주세요

2020-08-25 03:23 UTC, soheon-lee commented on user/urls.py
> +    path('signin',SignInView.as_view())
```suggestion
    path('/signup',SignUpView.as_view()),
    path('/signin',SignInView.as_view())
```

2020-08-25 03:23 UTC, soheon-lee commented on user/views.py
> +
배포용 코드에는 이러한 확인용 코드가 있어서는 안됩니다. 이러 엔드포인트가 존재하면 아무나 get으로 호출해서 우리 서버에 저장된 사용자의 정보를 읽어볼 수 있다는 뜻입니다. 보안에 대해 전혀 고려하지 않은 API 입니다. 삭제해주세요~

2020-08-25 03:23 UTC, soheon-lee commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status = 401)
else를 사용하지 않아도 위 if문이 만족하지 않아서 return되지 않는다면 아래 로직에 도달하게 됩니다.
따라서 굳이 필요하지 않은 else는 사용하지 않는 것이 보다 파이썬답습니다

2020-08-26 07:40 UTC, lordmyshepherd requested changes

2020-08-26 07:40 UTC, lordmyshepherd commented on user/views.py
>                      return JsonResponse({"message" :"LOGIN_SUCESS", "token" : token}, status=200)
현우님 `access_token`만 전달해주셔도 충분할 것 같습니다!
access token을 받았고 status_code=200 이기 때문에 `"message" :"LOGIN_SUCESS"` 불필요한 메세지인 것 같습니다~

2020-08-26 07:40 UTC, lordmyshepherd commented on user/views.py
>                      token = jwt.encode({"id" : get_user.id}, SECRET_KEY['secret'], ALGORITHM_KEY['algorithm']).decode('utf-8')
`access_token`으로 정확히 변수명을 수정해주세요~

2020-08-26 11:07 UTC, soheon-lee commented
LGTM 👍

2020-08-26 11:07 UTC, merged